name: crop_care
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.10.1
  image_picker: ^1.0.4
  tflite_v2: ^1.0.0
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  animated_splash_screen: ^1.3.0
  image:
  url_launcher: ^6.1.14
  google_nav_bar: ^5.0.6
  dialog_flowtter: ^0.3.3
  flutter_tts: ^3.8.3
  velocity_x:
  http:
  shared_preferences:
  jwt_decoder:
  flutter_slidable:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite
    - assets/classes.txt
    - assets/
    - images/community_suport.png
    - images/disease_detection_img.png
    - images/expert_support_img_1.png
    - images/image_6.png
    - images/image_7.png
    - images/bg.png
    - images/expert_guidance.png
    - images/playstore.png
    - images/image19.png
    - images/farmer1.png
    - images/expert2.png
    - images/kisanyojna.png
    - images/pyojna.png
    - images/enumyojna.png
    - images/bhandaryojna.png
    - images/p-1.png
    - images/p-2.png
  fonts:
    - family: InterB
      fonts:
        - asset: fonts/Inter-Bold.ttf
    - family: Lora
      fonts:
        - asset: fonts/Lora-VariableFont_wght.ttf
    - family: Merriweather
      fonts:
        - asset: fonts/Merriweather-Regular.ttf
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf